### PR TITLE
Add scatter figure test

### PR DESCRIPTION
**Pull request by dstansby**
Adds a figure test for scattering two images against each other.

The fix to previous issues we were having was adding the line `widget = ScatterWidget(viewer)`. For some reason, storing the widget in a variable instead of just doing `figure = ScatterWidget(viewer).figure` makes the callbacks work properley... I'm not entirely sure why, and I don't propose to enter that rabbit hole.

### CODE REVIEW

**Review by ruaridhg — APPROVED** [review]
Works for me locally!

**Comment by dstansby** [comment]
I'm guessing that's because the selected layers are stored in a `set()`, which doesn't guarentee the order of layers. Let me see if I can think of a fix for the tests.

**Comment by dstansby** [comment]
To give the layers a deterministic order, I've sorted them by their name - do you think that's a good soluiton?

**Comment by ruaridhg** [comment]
> To give the layers a deterministic order, I've sorted them by their name - do you think that's a good soluiton?

It works for the tests, but does that mean that it will always plot based on alphabetical order rather than order of selecting within napari? I guess it's probably worth merging perhaps for now

**Review by ruaridhg — APPROVED** [review]
It works for the tests, but does that mean that it will always plot based on alphabetical order rather than order of selecting within napari? I guess it's still probably worth merging for now

**Pull request merged**
