### PR TITLE
Color histogram bars

### LINKED ISSUE #58: Make a feature histogram exploration widget
## Feature proposal

Hi @dstansby ,

I created a feature exploration widget in a [different repository](https://github.com/BiAPoL/napari-stress) together with @zoccoler which shows a `Layer.features` in a histogram along with the cumulative density function. I think it would make sense to move it upstream (e.g., here) - what do you think of it?

Here's a small demo of how it looks/works:
ezgif com-gif-maker

The plugin is currently inheriting from `HistogramWidget`.

### PR DESCRIPTION
**Pull request by jo-mueller**
@dstansby 

Fixes #58 

This PR expands the feature histogram widget to color the histogram bars according to the color values in the displayed layer. Currently supported:

- Points layer
- Vectors layer

I'm not sure how tracks/shapes layer handle features and color, but this can be added relatively easily [here](https://github.com/jo-mueller/napari-matplotlib/blob/b6312c36573c8707f0ecec0f097898e0615a740f/src/napari_matplotlib/histogram.py#L167).

## Tests

- Pytest: I rewrote the existing tests a bit to make them more specific to vectors/points/other future supported layer and updated the respective baseline images. However, I didn't get the tests to pass with the call to `pytest --mpl` - it's probably the same issue as in [this](https://github.com/matplotlib/napari-matplotlib/pull/148) PR.
- Interactive test: I checked in the viewer that all controls behave as expected.

### CODE REVIEW

**Comment by jo-mueller** [comment]
pre-commit.ci autofix

**Comment by dstansby** [comment]
I've just fixed some failing tests (due to a new Matplotlib release) at https://github.com/matplotlib/napari-matplotlib/pull/217, so worth merging or rebasing main.

**Comment by jo-mueller** [comment]
@dstansby

Strange. The figures in the `baseline` folders were saved from the tests themselves using 

```python
deepcopy(fig).savefig('./baseline/name_of_test_function.png')
```

As for the other failing tests, I merged the current head into this branch but am not sure why tests are failing.

**Comment by jo-mueller** [comment]
Hi @dstansby ,

could you give me a hint on how to properly create the figures needed for the test to make the checks pass? Would be much appreciated :)

**Comment by dstansby** [comment]
I *think* the test figures were in the right place, but just needed updating due to changes that happened between opening the PR and now. I've merged in main, and updated the figures, so lets see if the tests pass now 😄

**Pull request merged**
