### PR TITLE
Add feature histogram widget

### PR DESCRIPTION
**Pull request by haesleinhuepf**
Hi @dstansby ,

this adds a FeatureHistogramWidget to napari-matplotlib to visualize quantitative measurements that have been stored in labels layers in napari. If that's out of scope, no problem, we could easily also put this code in [napari-clusters-plotter](https://github.com/BiAPoL/napari-clusters-plotter) or [napari-skimage-regionprops](https://github.com/haesleinhuepf/napari-skimage-regionprops). I just thought it fits best here.

image

Let me know what you think. Thanks!

Best,
Robert

### CODE REVIEW

**Comment by dstansby** [comment]
Thanks for opening this PR - I'm busy with other projects at the moment (sorry 😞 ), but have funding to work on `napari-matplotlib` at the beginning of 2023, so I will get back to you then - at a glance this looks like a nice feature to have though 😃

**Comment by haesleinhuepf** [comment]
Hey @dstansby ,

thanks for your reply and congratulations to the grant! There's no hurry. Looking forward to 2023 🙌

**Comment by haesleinhuepf** [comment]
Correct!

**Review by dstansby — CHANGES_REQUESTED** [review]
Looks 👍 overall. I've left a few requests to remove stuff, that we should consider more generally for all the plots `napari-matplotlib` produces.

**Comment by dstansby** [comment]
I'm going to close this in favour of https://github.com/matplotlib/napari-matplotlib/pull/148

**Pull request closed without merging**
