### PR TITLE
Allow user-defined stylesheets.

### PR DESCRIPTION
**Pull request by samcunliffe**
Minimal code-change solution to #2.

As discussed off-issue, I've gone for an (oversimplified) UI: our user puts their custom theme in cwd with the name `user.mplstyle`. I expect we want to refine this (hence a draft PR at the moment).

### CODE REVIEW

**Comment by dstansby** [comment]
Seems like a good first approach.

Could you check that this doesn't break https://github.com/matplotlib/napari-matplotlib/issues/64 again? I suspect that setting the stylesheet globally (which as far as I know is all that can be done in Matplotlib 😢 ) might resurface that. If it does, we might have to discuss either dropping this new feature, or finding a way to parse the style sheet and manually apply the styles to the figure/axes.

**Comment by dstansby** [comment]
Or what we might be able to do is set the style sheet, plot, then reset to the previous style sheet directly after plotting.

**Comment by samcunliffe** [comment]
> set the style sheet, plot, then reset to the previous style sheet directly after plotting.

Good old MPL devs have provided a [context manager](https://matplotlib.org/stable/api/style_api.html#matplotlib.style.context). P'raps this helps....

**Comment by samcunliffe** [comment]
Still WIP (and as-is, this does re-introduce #64).
Failing test first, for proof.

**Comment by dstansby** [comment]
Succeeded by https://github.com/matplotlib/napari-matplotlib/pull/181, but I did cherry-pick the test from here 🪄

**Pull request closed without merging**
